[build] new makemore

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,12 +1,16 @@
 #!/bin/bash
 
+AWK=awk
+GREP=grep
+SED=sed
+MAKE=make
 CONFIG=config
 CONFIGURE_STATUS=configure.status
 out=$CONFIGURE_STATUS
 
 prefix=/usr/local
 function argument {
-	echo ${1} | awk 'BEGIN { FS = "="} {print $2}'
+	echo ${1} | ${AWK} 'BEGIN { FS = "="} {print $2}'
 }
 
 function help {
@@ -28,9 +32,9 @@ function help {
 	printf "\nFeatures enabling:\n"
 	for option in $OPTIONS
 	do
-		default=$(echo $option | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print $2}')
+		default=$(echo $option | ${SED} 's/_/-/g' | ${SED} 's/=/ /g' | ${AWK} '{print $2}')
 		if [ "$default" == "y" -o  "$default" == "n" ]; then
-			enable=$(echo $option | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print "--enable-"tolower($1)}')
+			enable=$(echo $option | ${SED} 's/_/-/g' | ${SED} 's/=/ /g' | ${AWK} '{print "--enable-"tolower($1)}')
 			if [ $(echo $enable | wc -c) -ge 17 ]; then
 				printf "\t$enable\tdefault:$default\n"
 			else
@@ -41,9 +45,9 @@ function help {
 	printf "\nFeatures:\n"
 	for option in $OPTIONS
 	do
-		default=$(echo $option | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print $2}')
+		default=$(echo $option | ${SED} 's/_/-/g' | ${SED} 's/=/ /g' | ${AWK} '{print $2}')
 		if [ "$default" != "y" -a  "$default" != "n" ]; then
-			with=$(echo $option | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print "--with-"tolower($1)}')
+			with=$(echo $option | ${SED} 's/_/-/g' | ${SED} 's/=/ /g' | ${AWK} '{print "--with-"tolower($1)}')
 			printf "\t$with=<value>\tdefault:$default\n"
 		fi
 	done
@@ -54,7 +58,8 @@ if [ ! -e ${CONFIG} -a -e default.config ]; then
 	cp default.config ${CONFIG}
 fi
 
-OPTIONS=$(cat ${CONFIG} | sed 's/\#.*//g')
+OPTIONS=$(cat ${CONFIG} | ${SED} 's/\#.*//g')
+error=n
 
 while [ "${1}" != "" ]; do
 	case ${1} in
@@ -85,20 +90,23 @@ while [ "${1}" != "" ]; do
 		--sysroot*)
 			sysroot=$(argument ${1})
 			;;
+		--disable-error)
+			error=disable
+			;;
 		--help*)
 			help
 			;;
 		*)
 			found=n
-			OPTION=$(echo ${1} | sed 's/=/ /g' | gawk '{print $1}')
+			OPTION=$(echo ${1} | ${SED} 's/=/ /g' | ${AWK} '{print $1}')
 			for opt in $OPTIONS
 			do
-				default=$(echo $opt | sed 's/=/ /g' | gawk '{print $2}')
-				option=$(echo $opt | sed 's/=/ /g' | gawk '{print $1}')
+				default=$(echo $opt | ${SED} 's/=/ /g' | ${AWK} '{print $2}')
+				option=$(echo $opt | ${SED} 's/=/ /g' | ${AWK} '{print $1}')
 
-				enable=$(echo $opt | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print "--enable-"tolower($1)}')
-				disable=$(echo $opt | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print "--disable-"tolower($1)}')
-				with=$(echo $opt | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print "--with-"tolower($1)}')
+				enable=$(echo $opt | ${SED} 's/_/-/g' | ${SED} 's/=/ /g' | ${AWK} '{print "--enable-"tolower($1)}')
+				disable=$(echo $opt | ${SED} 's/_/-/g' | ${SED} 's/=/ /g' | ${AWK} '{print "--disable-"tolower($1)}')
+				with=$(echo $opt | ${SED} 's/_/-/g' | ${SED} 's/=/ /g' | ${AWK} '{print "--with-"tolower($1)}')
 
 				if [ "$enable" == "$OPTION" ]; then
 					default=y
@@ -115,51 +123,46 @@ while [ "${1}" != "" ]; do
 				NEWOPTIONS="$NEWOPTIONS ${option}=${default}"
 			done
 			OPTIONS=$NEWOPTIONS
-			if [ $found == n ]; then
-				printf "\x1B[31m\n\tbad argument: ${1}\n\n\x1B[0m"
-				help
+			NEWOPTIONS=""
+			if [ $found == n -a $error == n ]; then
+				error=${1}
 			fi
 			;;
 	esac
 	shift
 done
 
-if [ -z ${bindir} ]; then
-	bindir=${prefix}/bin
-fi
-if [ -z ${sbindir} ]; then
-	sbindir=${prefix}/sbin
-fi
-if [ -z ${includedir} ]; then
-	includedir=${prefix}/include
-fi
-if [ -z ${libdir} ]; then
-	libdir=${prefix}/lib
-fi
-if [ -z ${sysconfdir} ]; then
-	sysconfdir=${prefix}/etc
-fi
-
-make check
-if [ $? != 0 ]; then
-	echo "binary dependences failed"
-	exit -1
+if [ $error != n  -a $error != disable ]; then
+	printf "\x1B[31m\n\tbad argument: ${error}\n\n\x1B[0m"
+	help
 fi
 
 echo "#Makemore 1.0" > $out
 printf "\nInstallation:\n"
-echo "prefix=\""$prefix"\"" >> $out
-printf " prefix:\t$prefix\n"
-echo "bindir=\""$bindir"\"" >> $out
-printf " bindir:\t$bindir\n"
-echo "sbindir=\""$sbindir"\"" >> $out
-printf " sbindir:\t$sbindir\n"
-echo "includedir=\""$includedir"\"" >> $out
-printf " includedir:\t$includedir\n"
-echo "libdir=\""$libdir"\"" >> $out
-printf " libdir:\t$libdir\n"
-echo "sysconfdir=\""$sysconfdir"\"" >> $out
-printf " sysconfdir:\t$sysconfdir\n"
+if [ $prefix ]; then
+	echo "prefix=\""$prefix"\"" >> $out
+	printf " prefix:\t$prefix\n"
+fi
+if [ $bindir ]; then
+	echo "bindir=\""$bindir"\"" >> $out
+	printf " bindir:\t$bindir\n"
+fi
+if [ $sbindir ]; then
+	echo "sbindir=\""$sbindir"\"" >> $out
+	printf " sbindir:\t$sbindir\n"
+fi
+if [ $includedir ]; then
+	echo "includedir=\""$includedir"\"" >> $out
+	printf " includedir:\t$includedir\n"
+fi
+if [ $libdir ]; then
+	echo "libdir=\""$libdir"\"" >> $out
+	printf " libdir:\t$libdir\n"
+fi
+if [ $sysconfdir ]; then
+	echo "sysconfdir=\""$sysconfdir"\"" >> $out
+	printf " sysconfdir:\t$sysconfdir\n"
+fi
 if [ $sysroot ]; then
 	echo "sysroot=\""$sysroot"\"" >> $out
 	printf " sysroot:\t$sysroot\n"
@@ -170,11 +173,22 @@ if [ $CROSS_COMPILER ]; then
 fi
 
 echo "# Configuration file set with ./configure" > ${CONFIG}
+for opt in $OPTIONS
+do
+	echo $opt >> ${CONFIG}
+done
+
+${MAKE} check 2> /dev/null
+if [ $? != 0 ]; then
+	echo "binary dependences failed"
+	exit -1
+fi
+
 printf "\nConfiguration:\n"
 for opt in $OPTIONS
 do
-	default=$(echo $opt | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print $2}')
-	option=$(echo $opt | sed 's/_/-/g' | sed 's/=/ /g' | gawk '{print $1}')
+	default=$(echo $opt | ${SED} 's/=/ /g' | ${AWK} '{print $2}')
+	option=$(echo $opt | ${SED} 's/=/ /g' | ${AWK} '{print $1}')
 	if [ $(echo $option | wc -c) -ge 15 ]; then
 		printf " $option:\t$default\n"
 	elif [ $(echo $option | wc -c) -ge 7 ]; then
@@ -182,5 +196,4 @@ do
 	else
 		printf " $option:\t\t\t$default\n"
 	fi
-	echo $opt >> ${CONFIG}
 done
